# Generated by Django 3.0.4 on 2020-03-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boba', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meet',
            name='address',
            field=models.CharField(default='stuff', max_length=100),
        ),
    ]
