# Generated by Django 3.0.4 on 2020-03-12 19:57

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('boba', '0003_auto_20200312_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='photo_url',
            field=s3direct.fields.S3DirectField(blank=True),
        ),
    ]
