# Generated by Django 3.0.4 on 2020-03-13 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boba', '0004_auto_20200312_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='photo_url',
            field=models.FileField(upload_to=''),
        ),
    ]
